"""add_organizer_id_to_events

Revision ID: 32d22e531b8d
Revises: 075dee26058f
Create Date: 2026-09-20 00:20:54.296206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d22e531b8d'
down_revision: Union[str, Sequence[str], None] = '075dee26058f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_foreign_key('fk_events_organizer_id_users', 'events', 'users', ['organizer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_events_organizer_id_users', 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_column('events', 'organizer_id')
    # ### end Alembic commands ###
